GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "example2"
}

###

DELETE http://localhost:3001/todo/647c63d8ba1b19f35d670afe

###

PUT http://localhost:3001/todo/complete/647c63d8ba1b19f35d670afe